name: CI
on: 
    push:
      branches: [ "main"]
   pull_request:
   branches: ["main"]
  

       job:
         build:
           runs-on: ubuntu-latest
       steps:
     - uses: actions/checkout@v4
     - name: Show repo contenes
      run: |
     pwd
     ls -la
     - name: Sample step
         run: echo "Hello from Github Actions"

